"""Constants for CodePet state calculation."""

# Default stats for new pets
DEFAULT_PET_STATS = {
    "satiety": 50,
    "energy": 50,
    "happiness": 50,
    "social": 50,
}

DEFAULT_REGROUND_THRESHOLD = 6
RECENT_ACTIVE_DAYS_LIMIT = 7
DEFAULT_SESSION_SPLIT_TIMEOUT_MINUTES = 45
SESSION_SPLIT_TIMEOUT_MINUTES_MIN = 30
SESSION_SPLIT_TIMEOUT_MINUTES_MAX = 90
MARATHON_THRESHOLD_MINUTES = 120
MARATHON_MIN_COMMITS = 3
MAX_DETECTED_SESSIONS = 5

# Timezone/circadian defaults for narrative-facing temporal context.
DEFAULT_TIMEZONE = "America/Chicago"
QUIET_HOURS_START = 23
QUIET_HOURS_END = 6
LATE_NIGHT_START = 22
LATE_NIGHT_END = 5
SLEEP_MIN_INACTIVE_HOURS = 2
