"""Constants for CodePet state calculation."""

# Default stats for new pets
DEFAULT_PET_STATS = {
    "satiety": 50,
    "energy": 50,
    "happiness": 50,
    "social": 50,
}

DEFAULT_REGROUND_THRESHOLD = 6
RECENT_ACTIVE_DAYS_LIMIT = 7
DEFAULT_SESSION_SPLIT_TIMEOUT_MINUTES = 45
SESSION_SPLIT_TIMEOUT_MINUTES_MIN = 30
SESSION_SPLIT_TIMEOUT_MINUTES_MAX = 90
MARATHON_THRESHOLD_MINUTES = 120
MARATHON_MIN_COMMITS = 3
MAX_DETECTED_SESSIONS = 5
